/**
 * Message levels.
 */
export enum Level {
  /**
   * Information or positive validation outcome.
   */
  INFO = "INFO",
  /**
   * Something that may or may not be a problem.
   */
  WARNING = "WARNING",
  /**
   * A problem.
   */
  ERROR = "ERROR",
  /**
   * A problem that force us to stop validation of curren resource.
   */
  CRITICAL = "CRITICAL",
}

export enum ResourceType {
  /**
   * URL to validate as provided by the user.
   */
  URL = "URL",
  /**
   * Dataset to validate.
   */
  DATASET = "DATASET",
}

/**
 * Represent a resource for validation.
 */
export class ResourceInValidation {
  url: string;

  type: ResourceType;

  constructor(url: string, type: ResourceType) {
    this.url = url;
    this.type = type;
  }
}

/**
 * Represent a basic validation unit a message.
 */
export interface Message {
  readonly created: Date;

  readonly level: Level;

  readonly validator: String;

  readonly message: String;
}

/**
 * Listener to the process of validation.
 */
export interface ValidationObserver {
  onMessage(message: Message): void;

  onResourceWillStart(resource: ResourceInValidation): void;

  onResourceDidEnd(resource: ResourceInValidation): void;
}

class ConsoleLogObserver implements ValidationObserver {
  onMessage(message: Message) {
    console.log("onMessage", message);
  }

  onResourceWillStart(resource: ResourceInValidation): void {
    console.log("onResourceWillStart", resource);
  }

  onResourceDidEnd(resource: ResourceInValidation): void {
    console.log("onResourceDidEnd", resource);
  }
}

/**
 * Represent a full object generated by validation.
 * The report is build using messaged that a client can listen
 * to using {@link ValidationObserver}.
 */
export class ValidationReporter {
  private readonly observer: ValidationObserver;

  private resources: ResourceInValidation[] = [];

  constructor(observer?: ValidationObserver) {
    this.observer = observer ?? new ConsoleLogObserver();
  }

  private emitMessage(level: Level, validator: String, message: String): void {
    this.observer.onMessage({
      created: new Date(),
      level: level,
      validator: validator,
      message: message,
    });
  }

  info(validator: String, message: String): void {
    this.emitMessage(Level.INFO, validator, message);
  }

  warning(validator: String, message: String): void {
    this.emitMessage(Level.WARNING, validator, message);
  }

  error(validator: String, message: String): void {
    this.emitMessage(Level.ERROR, validator, message);
  }

  /**
   * Throws an exception to terminate validation.
   */
  critical(validator: String, message: String): void {
    this.emitMessage(Level.CRITICAL, validator, message);
  }

  private lastResource(): ResourceInValidation | undefined {
    return this.resources[this.resources.length - 1];
  }

  beginUrlValidation(url: string) {
    this.openResource(new ResourceInValidation(url, ResourceType.URL));
  }

  private openResource(resource: ResourceInValidation): void {
    this.observer.onResourceWillStart(resource);
    this.resources.push(resource);
  }

  beginDatasetValidation(url: string) {
    this.openResource(new ResourceInValidation(url, ResourceType.DATASET));
  }

  endResourceValidation() {
    const resource = this.resources.pop();
    this.observer.onResourceDidEnd(resource);
  }
}
